FROM php:8.3-apache

RUN mv "$PHP_INI_DIR/php.ini-development" "$PHP_INI_DIR/php.ini"

RUN apt update && apt install -y libxml2-dev zlib1g-dev libpng-dev

RUN a2enmod rewrite

RUN docker-php-ext-install mysqli dom intl simplexml session xml gd pdo pdo_mysql \
    && pecl install xdebug \
    && docker-php-ext-enable xdebug

EXPOSE 80
