version: '3'

services:
    silverstripe:
        build:
            dockerfile: ./Dockerfile.dev
            context: .
        ports:
            - '8080:80'
        volumes:
            - '.:/var/www/html'
    theme:
        build:
            dockerfile: ./Dockerfile.dev
            context: .
        ports:
            - '8888:80'
        volumes:
            - './theme:/var/www/html'