version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - '80:80'
    links:
      - 'php-fpm'
    volumes:
      - './:/var/www/html'
      - './.docker/nginx:/etc/nginx/conf.d'
    depends_on:
      - php-fpm

  php-fpm:
    build:
      dockerfile: './.docker/php-fpm/Dockerfile'
    volumes:
      - './:/var/www/vhosts/html'
      - './.docker/php-fpm/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini'
    expose:
      - '9000'

  mariadb:
    image: mariadb:10.9
    environment:
      MYSQL_DATABASE: 'wordpress'
      MYSQL_USER: 'wordpress'
      MYSQL_PASSWORD: 'wordpress'
      MYSQL_ROOT_PASSWORD: 'secret'
    volumes:
      - './.docker/data/database:/var/lib/mysql'
    ports:
      - '3306:3306'

  mailhog:
    image: mailhog/mailhog
    logging:
      driver: 'none'
    ports:
      - '8025:8025'