name: Release ${{ gitea.event.repository.name }}
run-name: ${{ gitea.actor }} - Release ${{ gitea.event.repository.name }}
on:
    push:
        branches:
            - main

jobs:
    release:
        runs-on: ubuntu-latest
        container:
            image: "ragnar.network:3000/mathijs/docker-dind:latest"
        steps:
            - name: Install container dependencies
              run: /bin/sh -c "apk add nodejs npm tar"
            - name: Check out repo
              uses: actions/checkout@v4
            - name: Log in to registry
              run: echo "${{ vars.DOCKER_REGISTRY_PASS }}" | docker login ragnar.network:3000 --username mathijs --password-stdin
            - name: Build static
              run: npm i && npm run build
            - name: Build image
              run: docker build -t ragnar.network:3000/${{ gitea.repository_owner }}/${{ gitea.event.repository.name }}:latest .
            - name: Push image
              run: docker push ragnar.network:3000/${{ gitea.repository_owner }}/${{ gitea.event.repository.name }}:latest
            - name: Cleanup old images
              run: docker image prune -f
